### ISSUE TITLE
[BUG] Playerlist makes appear 2 peoples

### ISSUE THREAD

**Issue by Betawolfy** [surepy/tf2_bot_detector#24]
**Describe the bug**
> When you place your mouse cursor at the right place between 2 people, you can see both. 

**To Reproduce**
> Steps to reproduce the behavior:
> 1. player list
> 2. place your cursor between 2 persons

**Expected behavior**
> only one people should appear.

**Logs**
> N/A

**Screenshots**
![image](https://github.com/surepy/tf2_bot_detector/assets/80059002/6bfb6da7-e33e-4267-af28-6d905299df99)

**Desktop (please complete the following information):**
> - OS: Windows 11 23H2
> - Version of bot detector : 1.5.13

**Additional context**
> Add any other context about the problem here.

**Comment by surepy** [comment]
what the

HAHAHAH application is literally unusable, gg

``MainWindow::OnDrawScoreboard`` uses an old columns api which is deprecated and legacy, I'll probably have to also move that to tables api when I look into this... (aka this wont be an instant fix)

Now I'm just curious if upgrading to imgui 1.90 recently caused this or this was a issue that existed in _all versions of bot detector_ but nobody realized until now because I did not touch that part of the code

for now uhhh pretend this issue doesn't exist and don't point on that overlapping pixel pls thanks

**Comment by Betawolfy** [comment]
i'll try on other version if i have time to kill
XDD ok!!
